### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "quack@gmail.com",
  "password": "asdfasdf"
}

### Find user with particular id
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@gmail.com

### Delete user with particular id
DELETE http://localhost:3000/auth/1

### Update user with particular id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "aaaaaa@aaaa.com"
}