### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "unique@gmail.com",
  "password": "asdfasdf"
}

### Create a new user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "unique@gmail.com",
  "password": "asdfaddddsdf"
}

### Find user with particular id
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=unique@gmail.com

### Delete user with particular id
DELETE http://localhost:3000/auth/3

### Update user with particular id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "aaaaaa@aaaa.com"
}

